### ISSUE TITLE
osg/Geometry: No such file or directory

### ISSUE THREAD

**Issue by eyildiz-ugoe** [allanschottler/Mesh-Completion#1]
Upon initiating `make`, one receives the titled error.

```
In file included from src/BoundaryGeometry.cpp:10:0:
src/BoundaryGeometry.h:11:10: fatal error: osg/Geometry: No such file or directory
 #include <osg/Geometry>
          ^~~~~~~~~~~~~~
compilation terminated.
Makefile:52: recipe for target 'obj/BoundaryGeometry.o' failed
make: *** [obj/BoundaryGeometry.o] Error 1
```

**Comment by allanschottler** [comment]
> 
> 
> Upon initiating `make`, one receives the titled error.
> 
> ```
> In file included from src/BoundaryGeometry.cpp:10:0:
> src/BoundaryGeometry.h:11:10: fatal error: osg/Geometry: No such file or directory
>  #include <osg/Geometry>
>           ^~~~~~~~~~~~~~
> compilation terminated.
> Makefile:52: recipe for target 'obj/BoundaryGeometry.o' failed
> make: *** [obj/BoundaryGeometry.o] Error 1
> ```

You are probably missing some dependencies to run this. By looking in the Makefile I can see these are:
```
GTK+2.0 (and all its dependencies)
OSG3.2 (and all its dependencies)
OpenMesh
```
You will have to install these and adjust the paths in the Makefiles, where INCLUDE and LIBSDIR are defined, to match the paths where you installed the dependencies.
